### PR TITLE
reloading fix ? maybe btw is worng offset

### PR DESCRIPTION
**Pull request by RetracedFn**

### CODE REVIEW

**Comment by Therealsxlar** [comment]
already tried using volcano's reload system even with the right offset it doesn't work 🤷‍♂️

**Comment by RetracedFn** [comment]
lol btw i added lategame using volcano code but is using wrong offset should work just change offset i testing smh

**Comment by Therealsxlar** [comment]
i'll eventually do lategame without volcano, for now im going to attempt to fix reloading

**Comment by RetracedFn** [comment]
MY LATEGAME WORK PERFECT JUST CRASH BC OFFSET LOL


image

**Comment by Therealsxlar** [comment]
thank you!

**Comment by RetracedFn** [comment]
np i will say thx if u fix my lategame offset lol is not on the dump 😢

**Comment by RetracedFn** [comment]
yo u want the imguii i added a imgui menu i working to make options like start bus etc


image

**Comment by Therealsxlar** [comment]
i don't need the extra stuff currently thank you though. I just need reloading working so I can finish this

**Comment by RetracedFn** [comment]
okok mb mb can u do me a fabor plz i get respawn working but i dont know how to dump offsets in og fn

        VirtualHook(FortPlayerControllerAthenaDefault->Vft, 0x458, ServerClientIsReadyToRespawn); // 8.51 offset
can u send this updated plzzzzzzzzzzzzzzzzzzzzzz ServerClientIsReadyToRespawn offset thx 💋

**Comment by RetracedFn** [comment]
or can u show me how to dump offsets plz xd i still learning

**Comment by RetracedFn** [comment]
i mean ik u need ida etc and dump game then add to ida but when ur on ida how i find the offset i want this is what i dont undestned

**Comment by RetracedFn** [comment]
image
i have dump ready and all but dont know how to find the offsets plz tell me how to do it

**Pull request closed without merging**
